name = "bentossell-leaderboard"
main = "leaderboard.js"
compatibility_date = "2024-01-01"

# KV namespace binding
[[kv_namespaces]]
binding = "LEADERBOARD"
id = "f7e17ee2ec844712b29e91658c776bb9"
# preview_id = "REPLACE_WITH_PREVIEW_KV_ID"

# Optional: custom domain
# routes = [
#   { pattern = "leaderboard.bentossell.com/*", zone_name = "bentossell.com" }
# ]
